bookstore_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :novels do
    collection do
    get :search
    end
  end
  resources :sessions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/author.rb
class Author < ApplicationRecord
    has_many :novels
    validates :fname, presence: true
    validates :lname, presence: true
    validates :bio, presence:true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :novels
    validates :name, presence: true
end

bookstore_app/app/models/novel.rb
class Novel < ApplicationRecord
    belongs_to :author
    belongs_to :genre
    belongs_to :publisher
    validates :title, presence: true
    validates :genre_id, presence: true
    validates :author_id, presence: true
    validates :publisher_id, presence: true
    validates :isbn, presence: true
    validates :price, presence: true
    validates :publication, presence: true
    validates :format, presence: true
    validates :description, presence: true
    validates :pages, presence: true
end

bookstore_app/app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :novels
    validates :name, presence: true
    validates :country, presence: true
end

bookstore_app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  validates :userid, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
    end

    def index
        @books=Book.all
    end

    def show
        @book=Book.find(params[:id])
    end

    def create
        #render plain: params[:book].inspect
        @book=Book.new(book_params)
        @book.save
        redirect_to @book
    end 

    private
    def book_params
        params.require(:book).permit(:title, :price, :book_id, :publisher, :description, :number)
    end

end

bookstore_app/app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index
        @genres=Genre.all
    end

    def show
        @genre=Genre.find(params[:id])
    end

    def new
        @genre=Genre.new
        @novel=Novel.new
    end

    def create
        @genre = Genre.new(genre_params)

        #redirecting to genre url when successfully created
        if @genre.save
            redirect_to genres_path
        else
            render 'new'
        end

    end

    def update
    end

    def edit
    end

    def destroy
    end

    private 
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

bookstore_app/app/controllers/novels_controller.rb
class NovelsController < ApplicationController

    before_action :authorize, :only => [ :create]

    def index
        @novels=Novel.all
        @genre=Genre.all
    end

    def show
        @novel=Novel.find(params[:id])
        @genre=Genre.find(params[:id])
    end

    def new
        @novel=Novel.new
        @genre=Genre.new
        @author=Author.new
        @publisher=Publisher.new
    end

    def create
        @novel = Novel.new(novel_params)
        if @novel.save
        redirect_to novels_path, notice:
        "You have successfully created a novel"
        else
        redirect_to novels_path, alert:
        "You will need to be signed in to create a novel"
        end
    end

    def update
        @novel = Novel.find(params[:id])
        if @novel.update(novel_params)
        redirect_to @novel
        else
        render 'edit'
        end
    end

    def edit
        @novel = Novel.find(params[:id])
    end

    def destroy
        @novel = Novel.find(params[:id])
        @novel.destroy
        redirect_to novels_path
    end

    def search
        @novels = if params[:term]
            #input parameter term = user input
            #potential site of SQL injection
            #Novel.where('title = ?', "%#{params[:term]}")

        Novel.where(["title = ?", "#{params[:term]}"])
        else
        Novel.all
        end
    end

    private 
    def novel_params
        params.require(:novel).permit(:title, :genre_id, :author_id, :publisher_id, :isbn, :price, :publication, :format, :description, :pages)
    end
    
end

bookstore_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
    end

    def new
        @user=User.new
    end

    def create
        
        @user=User.new(user_params)

        if @user.save
            #redirect to home here after user account creation
            redirect_to static_pages_home_path, notice:
            "Welcome #{@user.userid}! to Sheffield Book Store"
        else
            render 'new'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:userid, :email, :password, :password_confirmation)
    end

end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/genres_helper.rb
module GenresHelper
end

bookstore_app/app/helpers/novels_helper.rb
module NovelsHelper
end

bookstore_app/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/helpers/users_helper.rb
module UsersHelper
end

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookstoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

      <h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>

      <nav class="my-2 my-md-0 mr-md-3">

        <a class="p-2 text-dark" href="#"> <%= link_to "Home", '#'%> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "About Us", '#'%> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Contact Us", '#'%> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Add New Book", new_book_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Show Books", books_path %> </a>

      </nav>
      


    </div>
    <hr>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

    <h5 class="my-0 mr-md-auto font-weight-normal"> Tutorial App </h5>

    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#"> <%= link_to "Add New Author", new_author_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Show Authors", authors_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Add New Genre", new_genre_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Show Genres", genres_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Add New Publisher", new_publisher_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Show Publishers", publishers_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Add New Novel", new_novel_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Show Novels", novels_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Search Novels", search_novels_path %> </a>
      <a class="p-2 text-dark" href="#"> <%= link_to "Register", new_user_path %> </a>
    </nav>

    <% if current_user %>
    <a class="p-2 text-dark" href="#">
    <%= link_to 'Log out', session_path('active'), method: :delete %>
    </a>
    
    <a class="p-2 text-dark" href="#">
    <%= current_user.userid %>
    </a>
    
    <% else %>
    <a class="p-2 text-dark" href="#">
    <%= link_to 'Log in', new_session_path, class: "active_nav_link" %>
    </a>
    <% end %>

    </div>
    <%= yield %>
      
  </div>
    
  </body>
</html>