bookstore_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :novels do
    collection do
    get :search
    end
  end
  resources :sessions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/author.rb
class Author < ApplicationRecord
    has_many :novels
    validates :fname, presence: true
    validates :lname, presence: true
    validates :bio, presence:true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :novels
    validates :name, presence: true
end

bookstore_app/app/models/novel.rb
class Novel < ApplicationRecord
    belongs_to :author
    belongs_to :genre
    belongs_to :publisher
    validates :title, presence: true
    validates :genre_id, presence: true
    validates :author_id, presence: true
    validates :publisher_id, presence: true
    validates :isbn, presence: true
    validates :price, presence: true
    validates :publication, presence: true
    validates :format, presence: true
    validates :description, presence: true
    validates :pages, presence: true
end

bookstore_app/app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :novels
    validates :name, presence: true
    validates :country, presence: true
end

bookstore_app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  validates :userid, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

bookstore_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    def index
        @authors=Author.all
    end

    def show
        @author=Author.find(params[:id])
    end

    def new
        #needed for foreign key
        @author=Author.new
        @novel=Novel.new
    end

    def create
        @author = Author.new(author_params)

        #redirecting to author url when successfully created
        if @author.save
            redirect_to authors_path
        else
            render 'new'
        end

    end

    def update
    end

    def edit
    end

    def destroy
    end

    private 
    def author_params
        params.require(:author).permit(:fname, :lname, :bio)
    end


end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
    end

    def index
        @books=Book.all
    end

    def show
        @book=Book.find(params[:id])
    end

    def create
        #render plain: params[:book].inspect
        @book=Book.new(book_params)
        @book.save
        redirect_to @book
    end 

    private
    def book_params
        params.require(:book).permit(:title, :price, :book_id, :publisher, :description, :number)
    end

end

bookstore_app/app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index
        @genres=Genre.all
    end

    def show
        @genre=Genre.find(params[:id])
    end

    def new
        @genre=Genre.new
        @novel=Novel.new
    end

    def create
        @genre = Genre.new(genre_params)

        #redirecting to genre url when successfully created
        if @genre.save
            redirect_to genres_path
        else
            render 'new'
        end

    end

    def update
    end

    def edit
    end

    def destroy
    end

    private 
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

bookstore_app/app/controllers/novels_controller.rb
class NovelsController < ApplicationController

    before_action :authorize, :only => [ :create]

    def index
        @novels=Novel.all
        @genre=Genre.all
    end

    def show
        @novel=Novel.find(params[:id])
        @genre=Genre.find(params[:id])
    end

    def new
        @novel=Novel.new
        @genre=Genre.new
        @author=Author.new
        @publisher=Publisher.new
    end

    def create
        @novel = Novel.new(novel_params)
        if @novel.save
        redirect_to novels_path, notice:
        "You have successfully created a novel"
        else
        redirect_to novels_path, alert:
        "You will need to be signed in to create a novel"
        end
    end

    def update
        @novel = Novel.find(params[:id])
        if @novel.update(novel_params)
        redirect_to @novel
        else
        render 'edit'
        end
    end

    def edit
        @novel = Novel.find(params[:id])
    end

    def destroy
        @novel = Novel.find(params[:id])
        @novel.destroy
        redirect_to novels_path
    end

    def search
        @novels = if params[:term]
            #input parameter term = user input
            #potential site of SQL injection
            #Novel.where('title = ?', "%#{params[:term]}")

        Novel.where(["title = ?", "#{params[:term]}"])
        else
        Novel.all
        end
    end

    private 
    def novel_params
        params.require(:novel).permit(:title, :genre_id, :author_id, :publisher_id, :isbn, :price, :publication, :format, :description, :pages)
    end
    
end

bookstore_app/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

    def index
        @publishers=Publisher.all
    end

    def show
        @publisher=Publisher.find(params[:id])
    end

    def new
        @publisher=Publisher.new
        @novel=Novel.new
    end

    def create
        @publisher = Publisher.new(publisher_params)

        #redirecting to publisher url when successfully created
        if @publisher.save
            redirect_to publishers_path
        else
            render 'new'
        end

    end

    def update
    end

    def edit
    end

    def destroy
    end

    private 
    def publisher_params
        params.require(:publisher).permit(:name, :country)
    end

    
end

bookstore_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
    end

    def new
    end

    def create

        user=User.find_by_userid(params[ :userid])

        if user && user.authenticate(params[ :password])
        session[ :user_id]=user.id
        redirect_to root_path, notice:
        "Welcome #{user.userid}, you are now logged in"
        
        else
        render 'new', alert:
        "Invalid username and/or password"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice:
        "You have successfully logged out"
    end

end

bookstore_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
    end

    def new
        @user=User.new
    end

    def create
        
        @user=User.new(user_params)

        if @user.save
            #redirect to home here after user account creation
            redirect_to static_pages_home_path, notice:
            "Welcome #{@user.userid}! to Sheffield Book Store"
        else
            render 'new'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:userid, :email, :password, :password_confirmation)
    end

end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/genres_helper.rb
module GenresHelper
end

bookstore_app/app/helpers/novels_helper.rb
module NovelsHelper
end

bookstore_app/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/helpers/users_helper.rb
module UsersHelper
end

bookstore_app/app/views/authors/index.html.erb
<div class="container">

    <h2>Author List</h2>

    <table border="1" class="table">
        <tr>
            <th>Forename</th>
            <th>Surname</th>
            <th>Biography</th>
            <th>Author Page</th>
        </tr>

        <% @authors.each do |author| %>

        <tr>
            <td><%= author.fname%></td>
            <td><%= author.lname%></td>
            <td><%= author.bio%></td>
            <td><%= link_to 'Author Page', author_path(author) %></td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/authors/new.html.erb
<div class="container">
    <h2>Add New Author</h2>

    <%= form_for :author, url: authors_path do |f| %>
        
    <div class="form-group">
        <%= f.label :fname %><br />
        <%= f.text_field :fname, class:'form-control' %><br />

        <%= f.label :lname %><br />
        <%= f.text_field :lname, class:'form-control' %><br />

        <%= f.label :bio %><br />
        <%= f.text_area :bio, class:'form-control' %><br />
    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", authors_path, class:'btn btn-default' %>

    <% end %>
</div>

bookstore_app/app/views/authors/show.html.erb
<div class="container">

    <h3>Author Details</h3>

    <p>Forename: <%= @author.fname %> </p>
    <br>
    <br>
    <p>Surname: <%= @author.lname %> </p>
    <br>
    <br>
    <p>Biography: <%= @author.bio %> </p>
    <br>
    <br>

</div>

bookstore_app/app/views/books/index.html.erb
<div class="container">

    <h2>Books Available</h2>

    <table border="1" class="table">
        <tr>
            <th>Book Title</th>
            <th>Book Code</th>
            <th>Book Price</th>
            <th>Publisher</th>
            <th>Book Description</th>
            <th>Number Of Copies</th>
            <th>Book Page</th>
        </tr>

        <% @books.each do |book| %>

        <tr>
            <td><%= book.title%></td>
            <td><%= book.book_id%></td>
            <td><%= book.price%></td>
            <td><%= book.publisher%></td>
            <td><%= book.description%></td>
            <td></td>
            <td><%= link_to 'Book Page', book_path(book) %></td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/books/new.html.erb
<div class="container">
    <h1> Add New Book</h1>

    <%= form_for :book, url: books_path do |f| %>
        
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price %>
        <br>
        <br>
        <%= f.label :publisher %>
        <%= f.text_field :publisher_name %>
        <br>
        <br>
        <%= f.label :book_desciption %>
        <%= f.text_area :description %>
        <br>
        <br>
        <%= f.label :copies %>
        <%= f.number_field :num_of_copies %>
    </div>

    <div class="form-group">
        <%= f.submit %>
    </div>

    <% end %>
</div>

bookstore_app/app/views/books/show.html.erb
<div class="container">

    <h3>Book Details</h3>

    <p>ID: <%= @book.book_id %> </p>
    <br>
    <br>
    <p>Title: <%= @book.title %> </p>
    <br>
    <br>
    <p>Price: <%= @book.price %> </p>
    <br>
    <br>
    <p>Publisher: <%= @book.publisher %> </p>
    <br>
    <br>
    <p>Description: <%= @book.description %> </p>

</div>

bookstore_app/app/views/genres/index.html.erb
<div class="container">

    <h2>Genre List</h2>

    <table border="1" class="table">
        <tr>
            <th>Genre</th>
            <th>Genre Page</th>
        </tr>

        <% @genres.each do |genre| %>

        <tr>
            <td><%= genre.name%></td>
            <td><%= link_to 'Genre Page', genre_path(genre) %></td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/genres/new.html.erb
<div class="container">
    <h2>Add New Genre</h2>

    <%= form_for :genre, url: genres_path do |f| %>
        
    <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class:'form-control' %><br />

    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", authors_path, class:'btn btn-default' %>

    <% end %>
</div>

bookstore_app/app/views/genres/show.html.erb
<div class="container">

    <h3>Genre Details</h3>
    <br>
    <br>
    <p>Name: <%= @genre.name %> </p>
    <br>
    <br>


</div>

bookstore_app/app/views/novels/edit.html.erb
<div class="container">

    <h2>Edit Novel Details</h2>

    <%= form_for @novel do |f| %>
    
    <div class="form-group">

    <%= f.label :title %><br />
    <%= f.text_field :title, class:'form-control' %><br />

    <%= f.label :author %><br />
    <%= f.select :author_id, Author.all.collect {|x| [x.fname + ' '+ x.lname, x.id]}, {:include_blank => 'Select Author'},class:'form-control' %><br />

    <%= f.label :genre %><br />
    <%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br />
    
    <%= f.label :publisher %><br />
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.country, x.id]}, {:include_blank => 'Select Publisher'},class:'form-control' %><br />

    <%= f.label :isbn %><br />
    <%= f.text_field :isbn, class:'form-control' %><br />

    <%= f.label :price %><br />
    <%= f.number_field :price, class:'form-control' %><br />

    <%= f.label :publication %><br />
    <%= f.date_field :publication, class:'form-control' %><br />

    <%= f.label :format %><br />
    <%= f.text_field :format, class:'form-control' %><br />

    <%= f.label :description %><br />
    <%= f.text_area :description, class:'form-control' %><br />

    <%= f.label :pages %><br />
    <%= f.number_field :pages, class:'form-control' %><br />

    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", novels_path, class:'btn btn-default' %>

    <% end %>

</div>

bookstore_app/app/views/novels/index.html.erb
<div class="container">

    <h2>Novel List</h2>

    <table border="1" class="table">
        <tr>
            <th>Title</th>
            <th>Genre ID</th>
            <th>Author ID</th>
            <th>Publisher ID</th>
            <th>ISBN</th>
            <th>Price</th>
            <th>Publication</th>
            <th>Format</th>
            <th>Description</th>
            <th>Pages</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <% @novels.each do |novel| %>

        <tr>
            <td><%= novel.title%></td>
            <td><%= novel.genre_id%></td>
            <td><%= novel.author_id%></td>
            <td><%= novel.publisher_id%></td>
            <td><%= novel.isbn%></td>
            <td><%= novel.price%></td>
            <td><%= novel.publication%></td>
            <td><%= novel.format%></td>
            <td><%= novel.description%></td>
            <td><%= novel.pages%></td>
            <td><%= link_to 'Show', novel_path(novel) %></td>
            <td><%= link_to 'Edit', edit_novel_path(novel) %> </td>
            <td><%= link_to 'Delete', novel_path(novel), method: :Delete, data: {confirm: "Are you sure you want to delete details"}%> </td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/novels/new.html.erb
<div class="container">

    <h2>Add New Novel</h2>

    <%= form_for :novel, url: novels_path do |f| %>
        
    <div class="form-group">

    <%= f.label :title %><br />
    <%= f.text_field :title, class:'form-control' %><br />

    <%= f.label :author %><br />
    <%= f.select :author_id, Author.all.collect {|x| [x.fname + ' '+ x.lname, x.id]}, {:include_blank => 'Select Author'},class:'form-control' %><br />

    <%= f.label :genre %><br />
    <%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br />
    
    <%= f.label :publisher %><br />
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.country, x.id]}, {:include_blank => 'Select Publisher'},class:'form-control' %><br />

    <%= f.label :isbn %><br />
    <%= f.text_field :isbn, class:'form-control' %><br />

    <%= f.label :price %><br />
    <%= f.number_field :price, class:'form-control' %><br />

    <%= f.label :publication %><br />
    <%= f.date_field :publication, class:'form-control' %><br />

    <%= f.label :format %><br />
    <%= f.text_field :format, class:'form-control' %><br />

    <%= f.label :description %><br />
    <%= f.text_area :description, class:'form-control' %><br />

    <%= f.label :pages %><br />
    <%= f.number_field :pages, class:'form-control' %><br />

    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", novels_path, class:'btn btn-default' %>

    <% end %>

</div>

bookstore_app/app/views/novels/search.html.erb
<div class="container">

    <%= form_tag search_novels_path, method: :get do %>

    <%= text_field_tag :term, nil, placeholder: 'Search', class:'form-control' %>
    
    <%= submit_tag "Search", class:'btn btn-default' %>
    
    <% end %>

    <h2>Novel List</h2>

    <table border="1" class="table">
        <tr>
            <th>Title</th>
            <th>Genre ID</th>
            <th>Author ID</th>
            <th>Publisher ID</th>
            <th>ISBN</th>
            <th>Price</th>
            <th>Publication</th>
            <th>Format</th>
            <th>Description</th>
            <th>Pages</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <% @novels.each do |novel| %>

        <tr>
            <td><%= novel.title%></td>
            <td><%= novel.genre_id%></td>
            <td><%= novel.author_id%></td>
            <td><%= novel.publisher_id%></td>
            <td><%= novel.isbn%></td>
            <td><%= novel.price%></td>
            <td><%= novel.publication%></td>
            <td><%= novel.format%></td>
            <td><%= novel.description%></td>
            <td><%= novel.pages%></td>
            <td><%= link_to 'Show', novel_path(novel) %></td>
            <td><%= link_to 'Edit', edit_novel_path(novel) %> </td>
            <td><%= link_to 'Delete', novel_path(novel), method: :Delete, data: {confirm: "Are you sure you want to delete details"}%> </td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/novels/show.html.erb
<div class="container">

    <h3>Novel Details</h3>
    <br>
    <br>
        <p>Title: <%= @novel.title %> </p>
    <br>
    <br>
        <p>ISBN: <%= @novel.isbn %> </p>
    <br>
    <br>
        <p>Price: <%= @novel.price %> </p>
    <br>
    <br>
        <p>Publication: <%= @novel.publication %> </p>
    <br>
    <br>
        <p>Format: <%= @novel.format %> </p>
    <br>
    <br>
        <p>Description: <%= @novel.description %> </p>
    <br>
    <br>
        <p>Pages: <%= @novel.pages %> </p>
    <br>
    <br>

</div>

bookstore_app/app/views/publishers/index.html.erb
<div class="container">

    <h2>Publisher List</h2>

    <table border="1" class="table">
        <tr>
            <th>Publisher</th>
            <th>Country</th>
            <th>Publisher Page</th>
        </tr>

        <% @publishers.each do |publisher| %>

        <tr>
            <td><%= publisher.name%></td>
            <td><%= publisher.country%></td>
            <td><%= link_to 'publisher Page', publisher_path(publisher) %></td>
        </tr>
        <% end %>
    </table>
    
</div>

bookstore_app/app/views/publishers/new.html.erb
<div class="container">
    <h2>Add New Publisher</h2>

    <%= form_for :publisher, url: publishers_path do |f| %>
        
    <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class:'form-control' %><br />

        <%= f.label :country %><br />
        <%= f.text_field :country, class:'form-control' %><br />

    </div>

    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", publishers_path, class:'btn btn-default' %>

    <% end %>
</div>

bookstore_app/app/views/publishers/show.html.erb
<div class="container">

    <h3>Publisher Details</h3>
    <br>
    <br>
        <p>Name: <%= @publisher.name %> </p>
    <br>
    <br>
        <p>Country: <%= @publisher.country %> </p>
    <br>
    <br>

</div>

bookstore_app/app/views/users/index.html.erb
<div class="container">
<h2> Registered Users </h2>
</div>

bookstore_app/app/views/users/new.html.erb
<div class="container">
    <h2>Create User Account</h2>
    <%= form_for @user do |f| %>

    <div class="field" style="100%">
        <% if @user.errors.any? %>
    <div id="error_explanation">
    <h2>
    <%= pluralize(@user.errors.count, "error") %>
    prohibted this from being saved:
    </h2>

    <p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li>
    <%= msg %>
    </li>
    </ul>
    <% end %>
    </p>

    <% if alert %>
    <%= alert %>
    <% end %>
    </div>
    <% end %>

    <%= f.text_field :userid, placeholder: 'Enter a Username', class: 'form-control' %>
    <%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
    <%= f.password_field :password, placeholder: 'Create a Password', class: 'form-control' %>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm your Password', class: 'form-control' %>
    <%= f.submit 'Create Account' %>
    <% end %>
    </div>
</div>